/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dougl
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bt_Adicionar = new javax.swing.JButton();
        Txt_valores = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_numeros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Entre com os números separados por espaço");

        Bt_Adicionar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Bt_Adicionar.setText("Enviar");
        Bt_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AdicionarActionPerformed(evt);
            }
        });

        Txt_valores.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        tbl_numeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Números Pares", "Números Ímpares"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_numeros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_valores, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bt_Adicionar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Txt_valores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(Bt_Adicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AdicionarActionPerformed
        
        Txt_valores.getText();
       
        
        //DECLARA UM ARRAY DE INTEIROS 
        ArrayList<Integer> arraypar = new ArrayList<Integer>();
        ArrayList<Integer> arrayimpar = new ArrayList<Integer>();
        
        
        ((DefaultTableModel) tbl_numeros.getModel()).setRowCount(0);
        
        //O tipo de dados long também é outro tipo de 
        //dados primitivo em Java com 8 bytes. Possui 
        //um intervalo mais amplo do que int para armazenar um 
        //número inteiro. O tipo de dados long é usado para 
        //conter o número inteiro maior que int não pode conter.
        
        
        String[] arrayValores = Txt_valores.getText().split(" ");       
          
        for (int i=0; i < arrayValores.length; i++) {
        String s = arrayValores[i];
        
        try {
            
        int numeroConvertido = Integer.parseInt(s);   
            
        Double.parseDouble(s);
        
        if(1 < numeroConvertido && numeroConvertido <= Math.pow(10,5)){
        
        if(numeroConvertido % 2 == 0){
        
            arraypar.add(numeroConvertido);
        
        }
        
        else{
        
            arrayimpar.add(numeroConvertido);
        
        }
        
        }
        
        else{
             
             JOptionPane.showMessageDialog(null, "Número fora do intervalo!!!", "Intervalo (1 < N <= 10^5)", JOptionPane.ERROR_MESSAGE);
             break;
        
        
        }
        
        
        }catch(NumberFormatException e) {
            
            JOptionPane.showMessageDialog(null, "Não é número!!!", "Número", JOptionPane.ERROR_MESSAGE);
            break;
            
        }
        
        
        
        }
        
        
        
        DefaultTableModel tabela_numeros = (DefaultTableModel) tbl_numeros.getModel();
         
        Collections.sort(arraypar);
        Collections.sort(arrayimpar, Collections.reverseOrder());
        
        
        for (int p=0; p < arraypar.size(); p++) {
            
        int par = arraypar.get(p);
        
        System.out.println("Números pares: " + par);
        
        
        Object[] dados = new Object[]{
 
            par
            
        };
        
        tabela_numeros.addRow(dados);
        
        
        }
        
        
        for (int im=0; im < arrayimpar.size(); im++) {
            
        int impar = arrayimpar.get(im);
        
        System.out.println("Números impar: " + impar);
        
        Object[] dados2 = new Object[]{
           "",
           impar 
            
        };
        
        tabela_numeros.addRow(dados2);
        
        }
        
        
        
        
         
        
    }//GEN-LAST:event_Bt_AdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Adicionar;
    private javax.swing.JTextField Txt_valores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_numeros;
    // End of variables declaration//GEN-END:variables
}
