/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dougl
 */
public class Tela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxT_valor = new javax.swing.JTextField();
        BT_Enviar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_notas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_moedas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Entre com o valor numérico");

        TxT_valor.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        BT_Enviar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BT_Enviar.setText("Enviar");
        BT_Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EnviarActionPerformed(evt);
            }
        });

        tbl_notas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOTAS:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_notas);

        tbl_moedas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MOEDAS:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_moedas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxT_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT_Enviar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TxT_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(BT_Enviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_EnviarActionPerformed
        
       float quantidade_nota; 
       
       float quantidade_moedas; 
       
       ((DefaultTableModel) tbl_notas.getModel()).setRowCount(0);
       ((DefaultTableModel) tbl_moedas.getModel()).setRowCount(0);
       
       String dados_da_moedas = null;
       
        //DECLARA UM ARRAY 
        ArrayList<Float> notas = new ArrayList<Float>();
        notas.add(100.00f); 
        notas.add(50.00f);
        notas.add(20.00f);
        notas.add(10.00f);
        notas.add(5.00f);
        notas.add(2.00f);
        
        ArrayList<Float> moedas = new ArrayList<Float>();
        moedas.add(1.00f); 
        moedas.add(0.50f);
        moedas.add(0.25f);
        moedas.add(0.10f);
        moedas.add(0.05f);
        moedas.add(0.01f);
       
        
        
       try{
           
       Float.parseFloat(TxT_valor.getText());
         
       float valor = Float.parseFloat(TxT_valor.getText());
       
       if(0 <= valor && valor <= 1000000.00){
       
       DefaultTableModel nota_na_tabela = (DefaultTableModel) tbl_notas.getModel();
       
       System.out.println("NOTAS:");
       
       for (int i=0; i < notas.size(); i++) {
           
       quantidade_nota = (valor / notas.get(i));
       
       int quantidade_nota1 = (int)quantidade_nota;
       
       
       String dados_da_nota = quantidade_nota1 + " nota(s) de R$: " + notas.get(i)+"0";
       
       Object[] dados = new Object[]{
 
            dados_da_nota
            
        };
        
       nota_na_tabela.addRow(dados);
       
       System.out.println(quantidade_nota1 + " nota(s) de R$: " + notas.get(i)+"0");
       
       valor = valor - (quantidade_nota1 * notas.get(i)); 
       
       }
       
         
       DefaultTableModel moedas_na_tabela = (DefaultTableModel) tbl_moedas.getModel();
       
       System.out.println("MOEDAS:");
       
       for (int M=0; M < moedas.size(); M++) {
           
       int casasDecimais = 2;
       BigDecimal aNumber = new BigDecimal(valor);
       aNumber = aNumber.setScale(casasDecimais, BigDecimal.ROUND_HALF_UP);	
       float value = (float) aNumber.doubleValue();
       
       float valor_redo1 = value; 
           
       quantidade_moedas = (valor_redo1 / moedas.get(M));
       
       int quantidade_moedas1 = (int)quantidade_moedas;
       
       
       if(moedas.get(M) == 1.0 || moedas.get(M) == 0.5 || moedas.get(M) == 0.10f){
       
       dados_da_moedas = quantidade_moedas1 + " moedas(s) de R$: " + moedas.get(M)+"0";
       System.out.println(quantidade_moedas1 + " moedas(s) de R$: " + moedas.get(M)+"0");
       
       }
       
       else{
       
         dados_da_moedas = quantidade_moedas1 + " moedas(s) de R$: " + moedas.get(M);
         System.out.println(quantidade_moedas1 + " moedas(s) de R$: " + moedas.get(M));
       
       }
       
       
       
       Object[] dados2 = new Object[]{
 
            dados_da_moedas
            
        };
        
       moedas_na_tabela.addRow(dados2);
       
       valor = valor_redo1 - (quantidade_moedas1 * moedas.get(M)); 
       
       }
       
       }
       
       else{
       
       JOptionPane.showMessageDialog(null, "Número fora do intervalo!!!", "Intervalo (0 ≤ N ≤ 1000000.00)", JOptionPane.ERROR_MESSAGE);
             
       
       }
        
       }catch(NumberFormatException e){
           
        JOptionPane.showMessageDialog(null, "Não é um número!!!", "Número", JOptionPane.ERROR_MESSAGE);   
        
        }

        
       
       
       
       
       
        
        
    }//GEN-LAST:event_BT_EnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Enviar;
    private javax.swing.JTextField TxT_valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_moedas;
    private javax.swing.JTable tbl_notas;
    // End of variables declaration//GEN-END:variables
}
